services:
  - type: web
    name: task-manager
    env: python
    buildCommand: pip install -r flask_app/requirements.txt
    startCommand: cd flask_app && gunicorn 'app:app'
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: SECRET_KEY
        generateValue: true