services:
  - type: web
    name: task-manager
    env: python
    plan: free
    buildCommand: pip install -r flask_app/requirements.txt
    startCommand: cd flask_app && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production