services:
  - type: web
    name: task-manager
    env: python
    plan: free
    buildCommand: pip install -r flask_app/requirements.txt
    startCommand: cd flask_app && gunicorn --workers 4 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: task_manager_db
          property: connectionString

databases:
  - name: task_manager_db
    plan: free
    ipAllowList: []